### PR TITLE
Fixed #1: improved query building support

### LINKED ISSUE #1: Add more functions to mlquery service
It is not feature complete yet, should ideally cover full structured query syntax:

http://docs.marklogic.com/guide/search-dev/structured-query#id_59265

### PR DESCRIPTION
**Pull request by grtjn**
Fixes #1, and testing of #4.

### CODE REVIEW

**Comment by grtjn** [comment]
I tried to remain backwards-compatible as much as possible. Exceptions:

- Meaning of collection() has changed from collection-constraint-query to collection-query (you now have a collectionConstraint function.
- Implementation of properties() was wrong, there is no such thing as a properties-query, so I changed that into properties-fragment-query (also exposed as propertiesFragment())

**Comment by joemfb** [comment]
This PR is being kept open for now, until all the methods within it are added as part of #14 and #15, at which point it will be closed.

**Comment by grtjn** [comment]
I could try rebasing, and redoing part of the work on top of your latest work. Not sure I'll be able to work on that on short notice. Feel free to open a PR of your own for it..

**Comment by joemfb** [comment]
I don't think it's worth your trouble. I want to split the work across multiple releases, need to add tests, verify signatures against the node-client-api, etc.

Still, the implementations are very valuable, and I'll use them as the basis for future PRs.

**Comment by joemfb** [comment]
This PR is fully covered by merged PRs #16 and #17, open PR #18, and open issue #20.

**Pull request closed without merging**
